name: OpenCL PoCL Tests (Full)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  pocl-full:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install OpenCL runtime
        run: |
          sudo apt-get update
          sudo apt-get install -y pocl-opencl-icd ocl-icd-opencl-dev opencl-headers clinfo
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --require-hashes -r requirements-full.txt
          pip install pyopencl
      - name: Run tests with PoCL
        env:
          PYOPENCL_COMPILER_OUTPUT: '1'
        run: python run-all-tests.py -vv
